name: 'Build & Tag'

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  check:
    uses: zenhelix/ci-workflows/.github/workflows/kotlin-library-check.yml@v5
    with:
      java-version: '21'

  create-tag:
    needs: check
    uses: zenhelix/ci-workflows/.github/workflows/gradle-create-tag.yml@v5
    with:
      java-version: '21'
    secrets: inherit
