name: 'Build'

on:
  pull_request: {}

jobs:
  check:
    uses: zenhelix/ci-workflows/.github/workflows/kotlin-library-check.yml@v3
    with:
      java-version: '21'

  label:
    uses: zenhelix/ci-workflows/.github/workflows/labeler.yml@v3
