name: 'Release'

on:
  push:
    tags: ['*']

permissions:
  contents: write

jobs:
  release:
    uses: zenhelix/ci-workflows/.github/workflows/kotlin-library-release.yml@v4
    with:
      java-version: '21'
      publish-command: './gradlew publish -Pversion=''${{ github.ref_name }}'''
    secrets: inherit
