name: 'Release'

on:
  push:
    tags: ['*']

jobs:
  release:
    uses: zenhelix/ci-workflows/.github/workflows/kotlin-library-release.yml@v2
    with:
      java-version: '21'
      publish-command: './gradlew publish -Pversion=''${{ github.ref_name }}'''
    secrets:
      MAVEN_SONATYPE_USERNAME: ${{ secrets.MAVEN_SONATYPE_USERNAME }}
      MAVEN_SONATYPE_TOKEN: ${{ secrets.MAVEN_SONATYPE_TOKEN }}
      MAVEN_SONATYPE_SIGNING_KEY_ID: ${{ secrets.MAVEN_SONATYPE_SIGNING_KEY_ID }}
      MAVEN_SONATYPE_SIGNING_PUB_KEY_ASCII_ARMORED: ${{ secrets.MAVEN_SONATYPE_SIGNING_PUB_KEY_ASCII_ARMORED }}
      MAVEN_SONATYPE_SIGNING_KEY_ASCII_ARMORED: ${{ secrets.MAVEN_SONATYPE_SIGNING_KEY_ASCII_ARMORED }}
      MAVEN_SONATYPE_SIGNING_PASSWORD: ${{ secrets.MAVEN_SONATYPE_SIGNING_PASSWORD }}
